---
name: Ansible collection linters
'on':
  workflow_call:
    inputs:
      lint_pip_dependencies:
        description: Python package dependencies for ansible-lint
        default: ""
        type: string
        required: false
jobs:
  lint:
    name: Ansible ${{ matrix.ansible }} lint
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - ansible: "2.12"
            # ansible-lint 6+ is not supported on Python 3.8.
            ansible-lint: "5"
            python: "3.8"
          - ansible: "2.14"
            ansible-lint: "6"
            python: "3.11"
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so it's accessible to the job
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core==${{ matrix.ansible }}.* ansible-lint==${{ matrix.ansible-lint }}.* ${{ inputs.lint_pip_dependencies }}

      - name: Linting code
        run: |
          ansible-lint -v --force-color

  sanity:
    name: Ansible ${{ matrix.ansible }} sanity
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - ansible: "2.12"
            python: "3.8"
          - ansible: "2.14"
            python: "3.11"

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so it's accessible to the job
      - uses: actions/checkout@v4
        with:
          path: repo

      # Checkout utility scripts
      - uses: actions/checkout@v4
        with:
          repository: stackhpc/.github
          path: stackhpc-github

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core==${{ matrix.ansible }}.*

      - name: Running sanity tests
        run: |
          $GITHUB_WORKSPACE/stackhpc-github/.github/workflows/collection-sanity.sh
        working-directory: ${{ github.workspace }}/repo
