name: Publish Collection
on:
  workflow_call:
jobs:
  galaxy:
    runs-on: ubuntu-latest
    name: Publish Ansible Collection to Ansible Galaxy
    steps:
      - name: Github Checkout 🛎
        uses: actions/checkout@v2
      - name: Build Collection 🛠
        run: ansible-galaxy collection build
      - name: Publish Collection 🚀
        run: ansible-galaxy collection publish *.tar.gz --api-key ${{ secrets.GALAXY_API_KEY }}
