---
name: Tag & Release
'on':
  push:
    branches:
      - "stackhpc/xena"
      - "stackhpc/wallaby"
      - "stackhpc/victoria"
  workflow_dispatch:
jobs:
  tag:
    runs-on: ubuntu-20.04
    env:
      naming-things-is-hard-repository: stackhpc/naming-things-is-hard
    name: Automatic tagging for ${{ github.ref_name }} 🏷
    steps:
      - name: Github checkout 🛎 [${{ github.repository }}]
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          fetch-depth: 0
      - name: Configure repository 🛠
        run: |
          git remote rename origin stackhpc &&
          git remote add origin "https://github.com/openstack/$(basename $(pwd)).git"
      - name: Push upstream tags to downstream fork 🏷
        run: |
          git fetch origin &&
          git push stackhpc --follow-tags
      - name: Github checkout 🛎 [${{ env.naming-things-is-hard-repository }}]
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          repository: ${{ env.naming-things-is-hard-repository }}
          path: naming-things-is-hard
      - name: Run naming-things-is-hard/os-downstream-tag
        run: naming-things-is-hard/os-downstream-tag.py --release $(basename $(git rev-parse --abbrev-ref HEAD))
  release:
    needs: [tag]
    runs-on: ubuntu-20.04
    name: Release newly generated tag 🏷
    steps:
      - name: Github checkout 🛎 [${{ github.repository }}]
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          fetch-depth: 0
      - name: Get tag 🏷
        id: commit-tag
        run: echo ::set-output name=value::$(git describe --tags --abbrev=0)
      - name: Generate release notes 📝
        run: git log --pretty="%h %s" $(git describe --tags --abbrev=0)...$(git describe --tags --abbrev=0 $(git describe --tags --abbrev=0)^) > changelog.txt
      - name: Publish release 🚀
        uses: softprops/action-gh-release@0465cdad11d833cabb6414f885edd2ccdfda4b96
        with:
          tag_name: ${{ steps.commit-tag.outputs.value }}
          body_path: ${{ github.workspace }}/changelog.txt
          files: |
            LICENSE
