---
name: Tag & Release
'on':
  workflow_call:
    inputs:
      upstream:
        description: Upstream repository URL
        type: string
        required: false
jobs:
  turnstyle:
    runs-on: ubuntu-20.04
    name: Serialise runs of this workflow
    permissions:
      actions: read
    steps:
      # Concurrent runs of this workflow can fail due to conflicting changes in tags.
      # The GitHub workflow concurrency option works to some degree, but only a
      # single job can be queued concurrently, and older queued jobs get
      # cancelled. This makes sense for a deployment, but not for a tagging
      # workflow.
      - name: Serialise runs of this workflow
        uses: softprops/turnstyle@ca99add00ff0c9cbc697d22631d2992f377e5bd5
        with:
          continue-after-seconds: 180
          poll-interval-seconds: 30
          same-branch-only: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tag:
    runs-on: ubuntu-20.04
    env:
      naming-things-is-hard-repository: stackhpc/naming-things-is-hard
    name: Automatic tagging for ${{ github.ref_name }} 🏷
    needs: [turnstyle]
    steps:
      - name: Github checkout 🛎 [${{ github.repository }}]
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure repository 🛠
        run: |
          upstream="${{ inputs.upstream }}"
          if [[ -z "$upstream" ]]; then
            upstream="https://github.com/openstack/$(basename $(pwd)).git"
          fi
          git remote rename origin stackhpc &&
          git remote add origin "$upstream"
      - name: Push upstream tags to downstream fork 🏷
        run: |
          git fetch origin &&
          git push stackhpc --follow-tags
      - name: Github checkout 🛎 [${{ env.naming-things-is-hard-repository }}]
        uses: actions/checkout@v4
        with:
          repository: ${{ env.naming-things-is-hard-repository }}
          path: naming-things-is-hard
      - name: Run naming-things-is-hard/os-downstream-tag
        run: naming-things-is-hard/os-downstream-tag.py --release $(basename $(git rev-parse --abbrev-ref HEAD))
  release:
    needs: [tag]
    runs-on: ubuntu-20.04
    name: Release newly generated tag 🏷
    steps:
      - name: Github checkout 🛎 [${{ github.repository }}]
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get tag 🏷
        id: commit-tag
        run: echo "value=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      - name: Generate release notes 📝
        run: git log --pretty="%h %s" $(git describe --tags --abbrev=0)...$(git describe --tags --abbrev=0 $(git describe --tags --abbrev=0)^) > changelog.txt
      - name: Publish release 🚀
        uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b
        with:
          tag_name: ${{ steps.commit-tag.outputs.value }}
          body_path: ${{ github.workspace }}/changelog.txt
          files: |
            LICENSE
