---
name: Tox Workflow
'on':
  workflow_call:
jobs:

  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      tox-matrix: ${{ steps.matrix.outputs.tox-matrix }}
    steps:
      - name: Define Tox matrix
        id: matrix
        env:
          PY3_8: ${{
                  (github.base_ref == 'stackhpc/yoga') ||
                  (github.ref == 'refs/heads/stackhpc/yoga') ||
                  (github.base_ref == 'stackhpc/zed') ||
                  (github.ref == 'refs/heads/stackhpc/zed') ||
                  (github.base_ref == 'stackhpc/2023.1') ||
                  (github.ref == 'refs/heads/stackhpc/2023.1') ||
                  (((github.base_ref == 'stackhpc/2024.1') ||
                  (github.ref == 'refs/heads/stackhpc/2024.1')) &&
                  (github.repository != 'stackhpc/kayobe'))
                  }}
          PY3_10: ${{
                  (github.base_ref == 'stackhpc/zed') ||
                  (github.ref == 'refs/heads/stackhpc/zed') ||
                  (github.base_ref == 'stackhpc/2023.1') ||
                  (github.ref == 'refs/heads/stackhpc/2023.1') ||
                  (github.base_ref == 'stackhpc/2024.1') ||
                  (github.ref == 'refs/heads/stackhpc/2024.1') ||
                  (github.base_ref == 'stackhpc/2025.1') ||
                  (github.ref == 'refs/heads/stackhpc/2025.1') ||
                  (github.base_ref == 'stackhpc/master') ||
                  (github.ref == 'refs/heads/stackhpc/master')
                  }}
          PY3_12: ${{
                  (github.base_ref == 'stackhpc/2025.1') ||
                  (github.ref == 'refs/heads/stackhpc/2025.1') ||
                  (github.base_ref == 'stackhpc/master') ||
                  (github.ref == 'refs/heads/stackhpc/master')
                  }}
          PEP8_8: ${{
                  (github.base_ref == 'stackhpc/yoga') ||
                  (github.ref == 'refs/heads/stackhpc/yoga')
                  }}
          PEP8_10: ${{
                  (github.base_ref == 'stackhpc/zed') ||
                  (github.ref == 'refs/heads/stackhpc/zed') ||
                  (github.base_ref == 'stackhpc/2023.1') ||
                  (github.ref == 'refs/heads/stackhpc/2023.1') ||
                  (github.base_ref == 'stackhpc/2024.1') ||
                  (github.ref == 'refs/heads/stackhpc/2024.1')
                  }}
          PEP8_12: ${{
                  (github.base_ref == 'stackhpc/2025.1') ||
                  (github.ref == 'refs/heads/stackhpc/2025.1') ||
                  (github.base_ref == 'stackhpc/master') ||
                  (github.ref == 'refs/heads/stackhpc/master')
                  }}
        run: |
          # Create a matrix based on the environment and Python minor version
          output="["
          if [[ $PY3_8 == 'true' ]]; then
              output+="{'environment': 'py3', 'python-minor-version': 8},"
          fi
          if [[ $PY3_10 == 'true' ]]; then
              output+="{'environment': 'py3', 'python-minor-version': 10},"
          fi
          if [[ $PY3_12 == 'true' ]]; then
              output+="{'environment': 'py3', 'python-minor-version': 12},"
          fi
          if [[ $PEP8_8 == 'true' ]]; then
              output+="{'environment': 'pep8', 'python-minor-version': 8},"
          fi
          if [[ $PEP8_10 == 'true' ]]; then
              output+="{'environment': 'pep8', 'python-minor-version': 10},"
          fi
          if [[ $PEP8_12 == 'true' ]]; then
              output+="{'environment': 'pep8', 'python-minor-version': 12},"
          fi
          # remove trailing comma
          output="${output%,}"
          output+="]"
          echo "tox-matrix=$output" >> $GITHUB_OUTPUT
         
  tox:
      runs-on: ubuntu-latest
      needs: define-matrix
      strategy:
        fail-fast: false
        matrix:
          include: ${{ fromJSON(needs.define-matrix.outputs.tox-matrix) }}

      name: Tox ${{ matrix.environment }} with Python 3.${{ matrix.python-minor-version }}
      steps:
        - name: Github Checkout 🛎
          uses: actions/checkout@v4
        - name: Setup Python 3.${{ matrix.python-minor-version }} 🐍
          uses: actions/setup-python@v5
          with:
            python-version: 3.${{ matrix.python-minor-version }}
        - name: Install bindep 📦
          run: |
            if [[ -f bindep.txt ]]; then
                pip install bindep
            else
                echo "No bindep.txt"
            fi
        - name: Install missing packages 📦
          run: |
            if [[ -f bindep.txt ]]; then
                sudo apt update && sudo apt install $(bindep -b test)
            else
                echo "No bindep.txt"
            fi
        - name: Install Tox 📦
          run: pip install tox
        - name: Run Tox pep8 🧪
          run: tox -e pep8
          if: ${{ matrix.environment == 'pep8' }}
        - name: Run Tox py3${{ matrix.python-minor-version }} 🧪
          run: tox -e py3${{ matrix.python-minor-version }}
          if: ${{ matrix.environment == 'py3' }}
