---
name: Upstream Sync Workflow
'on':
  workflow_call:
    inputs:
      release_series:
        description: 'The OpenStack release series you wish to sync against.'
        required: true
        type: string
env:
  GITHUB_TOKEN: ${{github.token}}
  DOWNSTREAM_OWNER: stackhpc
  UPSTREAM_OWNER: openstack
jobs:
  upstream-sync:
    runs-on: ubuntu-latest
    steps:
      -
